home:
    path: /
    controller: App\Controller\HomeController::index 

films:
    path: /films
    controller: App\Controller\FilmsController::index 

films.add:
    path: /films/new
    controller: App\Controller\FilmsController::add 

films.delete:
    path: /singlefilm/{slug}/{id}
    controller: App\Controller\FilmsController::delete
    methods: DELETE

singlefilm:
    path: /singlefilm/{slug}/{id}
    controller: App\Controller\FilmsController::single 
    methods: GET|POST


series:
    path: /series
    controller: App\Controller\SeriesController::index 

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
