home:
    path: /
    controller: App\Controller\HomeController::index 

films:
    path: /admin/films
    controller: App\Controller\FilmsController::index 

films.add:
    path: /admin/films/new
    controller: App\Controller\FilmsController::add 

films.delete:
    path: /admin/films/detail/{slug}/{id}
    controller: App\Controller\FilmsController::delete
    methods: DELETE

singlefilm:
    path: /admin/films/detail/{slug}/{id}
    controller: App\Controller\FilmsController::single 
    methods: GET|POST


series:
    path: /admin/series
    controller: App\Controller\SeriesController::index 

login:
    path: /login
    controller: App\Controller\SecurityController::login 

logout:
    path: /logout

tag:
    path: /admin/tag
    controller: App\Controller\TagController::index

tag.add:
    path: /admin/tag/new
    controller: App\Controller\TagController::new
   
tag.detail.edit:
    path: /admin/tag/{id}/edit
    controller: App\Controller\TagController::edit
  
tag.delete:
    path: /admin/tag/{id}
    controller: App\Controller\TagController::delete
    methods: DELETE
  
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
