home:
    path: /
    controller: App\Controller\HomeController::index 

films:
    path: /films
    controller: App\Controller\FilmsController::index 

series:
    path: /series
    controller: App\Controller\SeriesController::index 

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
