home:
    path: /
    controller: App\Controller\HomeController::index 

films:
    path: /films
    controller: App\Controller\FilmsController::index 

singlefilm:
    path: /singlefilm/{slug}/{id}
    controller: App\Controller\FilmsController::single 


series:
    path: /series
    controller: App\Controller\SeriesController::index 

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
